Neos:
  Fusion:
    defaultContext:
      Networkteam.ImageProxy: Networkteam\ImageProxy\Eel\SourceUriHelper

Networkteam:
  ImageProxy:
    # The imgproxy base URL
    imgproxyUrl: ''
    # The hex encoded key for imgproxy signatures
    key: ''
    # The hex encoded salt for imgproxy signatures
    salt: ''

    # Let imgproxy choose the file extension based on client preferences
    autoFormat: true

    # Format Quality, eg: 'jpg:75:avif:80:webp:70'
    formatQuality: ''

    # Media types that can be handled
    mediaTypes:
      'image/jpeg':
        enabled: true
      'image/png':
        enabled: true
      'image/gif':
        enabled: true
      'image/tiff':
        enabled: true
      'image/webp':
        enabled: true
      'image/avif':
        enabled: true
      'image/heic':
        enabled: true

    staticResources:
      # Enable for static resources
      enabled: false

      # No need to enable for Favicons
      ignoreRegexp: '/(favicon|apple-touch-icon)/'