Networkteam:
  ImageProxy:
    # The imgproxy base URL
    imgproxyUrl: 'http://localhost:8080'
    # The hex encoded key for imgproxy signatures
    key: ''
    # The hex encoded salt for imgproxy signatures
    salt: ''

    # Let imgproxy choose the file extension based on client preferences
    autoFormat: true

    # Format Quality, eg: 'jpg:75:avif:80:webp:70'
    formatQuality: ''
